---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
  name: tetris-namespace  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: adijaiswal/tetris:v1
          ports:
            - containerPort: 80


